models:
  - name: "blModel" # in the long run, the baseline model is the early exiting model but now it is the supervised model
    type: "bl"
    in_dim: 2
    feature_dim: 256
    num_classes: 10
    output_path: "./Models/blModel_100.pt"

  - name: "byolModel"
    type: "bl" # variants are: bl, eev0, eev1, eev2, eev3
    in_dim: 2
    feature_dim: 256
    num_classes: 10
    output_path: "./Models/fineTunedModel_50.pth"

  # - name: "byoleeModel"
  #   in_dim: 2
  #   feature_dim: 256
  #   num_classes: 10
  #   output_path: "/path/to/my_model2_output"
